### ISSUE TITLE
"Emulate from Current Node"

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#59] opened 2020-12-29 23:13 UTC
The Emulate from Current Node feature doesn't work consistently. Sometimes, it merely brings up a blank screen.

**Comment by danielanywhere** [comment] 2020-12-29 23:26
Duplicate of Issue 21 - https://github.com/AscendantDesign/Scaffold/issues/21

**Closed by danielanywhere** 2020-12-29 23:26 UTC
Labels: bug
